### ISSUE TITLE
Compat issue with Missing Wilds

### ISSUE THREAD

**Issue by Sunconure11** [Flemmli97/AdvancedGolems#2]
### Modloader

Fabric

### Minecraft version

1.18.2

### Modloader version

0.14.6

### Mod version

1.1.7

### TenshiLib version

1.6.7

### Description

https://github.com/UltrusBot/missing-wilds/issues/1

### Steps to reproduce

1. Attempt to boot up the game with Missing Wilds installed
2. ???
3. https://github.com/UltrusBot/missing-wilds/issues/1

### Mods that might affect the issue

Missing Wilds

### Logs

https://github.com/UltrusBot/missing-wilds/issues/1

**Comment by Flemmli97** [comment]
cannot reproduce. the game loads and runs fine on my end with only advanced golems + missing wilds

**Comment by Flemmli97** [comment]
closing since resolved i guess
