### ISSUE TITLE
Compatability with YungsbetterMineshafts and Polymer

### ISSUE THREAD

**Issue by valous2** [Flemmli97/AdvancedGolems#3]
### Modloader

Fabric

### Minecraft version

1.19.2

### Modloader version

Quilt Loader 0.17.6

### Mod version

advancedgolems-1.19-1.2.0-fabric.jar

### TenshiLib version

tenshilib-1.19-1.6.11-fabric.jar

### Description

I noticed that this mod when installed along side any of the Yungs better Mods and the mod polymer-all-0.2.18+1.19.2 will cause the server to crash on boot, even on a new world generation. I can install any combination of two of theses mods but as soon as I try the third it a no go.

I don't know which mod is causing this error so I am submitting this report to all three authors in hopes a fix can be made.

### Steps to reproduce

1. Step one: Install this mod, Polymer, and any of Yangs better mods.
2. Step two: Start server.

### Mods that might affect the issue

[Yungs Better Mineshafts](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-fabric/download/4031205)*
[Yungs Api](https://www.curseforge.com/minecraft/mc-mods/yungs-api-fabric/download/4035003)
[Cloth Api](https://www.curseforge.com/minecraft/mc-mods/cloth-config/download/3972420)
[Polymer](https://cdn.modrinth.com/data/xGdtZczs/versions/uZEwXh4D/polymer-all-0.2.18%2B1.19.2.jar)
[Quilt Fabric Api](https://cdn.modrinth.com/data/qvIfYCYJ/versions/zzHaJbi0/quilted-fabric-api-4.0.0-beta.19%2B0.64.0-1.19.2.jar)
[Advanced Golems](https://www.curseforge.com/minecraft/mc-mods/advanced-golems-fabric/download/4048644)
[Tenshi Lib](https://www.curseforge.com/minecraft/mc-mods/tenshilib-fabric/download/4033317)

*I have all of Yungs better mods installed but only takes one of them to produce an error.

### Logs

[log file](https://gist.github.com/valous2/b21c4abc1a20fb004a3daeb2464a709c)

**Comment by Flemmli97** [comment]
`Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [yungsbridges.mixins.json:SuppressLogMixin from mod yungsbridges] from phase [DEFAULT] in config [yungsbridges.mixins.json] FAILED during PREPARE` 
nothing to do with this mod from the logs. also since your using quilt you are kinda on your own. idk quilt

**Comment by Patbox** [comment]
Hey, the issue is possibly caused by your mod using MC class in you mixin plugin (most likely via your config). This will break any mod mixing into that class

**Comment by Flemmli97** [comment]
hmm i dont see me using any mc classes in my mixin config.
even the mixin themselfs dont target mc classes except for an accessor mixin which shouldnt break
